config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "products#index"
  resources :products
  post "checkout/create", to: "checkout#create"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, :price, :total_quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController

  def create
    local_product = Product.find(params[:id])
  
    # Create a Stripe Product
    stripe_product = Stripe::Product.create({
      name: local_product.title,
      type: 'good',  # You can adjust this based on your product type
    })
  
    # Create a Price object for the Stripe Product
    price = Stripe::Price.create({
      product: stripe_product.id,
      unit_amount: local_product.price * 100,  # convert price to cents
      currency: "usd",
    })
  
    # Create a Session with line_items using price_data
    @session = Stripe::Checkout::Session.create({
      payment_method_types: ['card'],
      line_items: [{
        price: price.id,
        quantity: 1
      }],
      mode: 'payment',
      success_url: root_url,
      cancel_url: root_url,
    })
  
    respond_to do |format|
      format.js  
    end
  end  

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :price, :total_quantity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/checkout/create.js.erb
<script>
var stripe = Stripe("<%= Rails.application.credentials[:stripe][:public] %>");

stripe.redirectToCheckout({
  sessionId: '<%= @session.id %>'
}).then(function (result) {
  console.log(result.error.message);
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StripeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://js.stripe.com/v3/"></script>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= link_to "Products", products_path %>
    <hr>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :total_quantity, style: "display: block" %>
    <%= form.number_field :total_quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>" >
  <p>
    <strong>Title:</strong>
    <%= product.title %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Total quantity:</strong>
    <%= product.total_quantity %>
  </p>

  <p>
    <%= button_to "Buy this", checkout_create_path, params: {id: product.id}, remote: true %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 style="text-align: center;">Products</h1>

<div id="products" style="display: flex; justify-content: center; align-items: center; flex-wrap: wrap;">
  <% @products.each do |product| %>
    <div style="margin: 10px; text-align: center;">
      <%= render product %>
      <p>
        <%= link_to "Show this product", product %>
      </p>
    </div>
  <% end %>
</div>

<div class="text-center">
  <%= link_to "New product", new_product_path %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>